# Generated by Django 3.1.3 on 2020-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20201211_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_Image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
